[versions]
agp = "8.7.1"
kotlin = "2.0.21"
core-ktx = "1.13.1"
junit = "4.13.2"
androidx-junit = "1.2.1"
espresso-core = "3.6.1"
splashscreen = "1.0.1"
constraint-layout-compose = "1.0.1"
lifecycle-runtime-ktx = "2.8.6"
activity-compose = "1.9.3"
material = "1.12.0"
material-icons-extended = "1.7.4"
multidex = "2.0.1"
retrofit = "2.11.0"
gson = "2.11.0"
logging-interceptor = "5.0.0-alpha.14"
paging-compose = "3.3.2"
landscapist = "2.4.1"
timber = "5.0.1"
navigation-compose = "2.8.3"
hilt-navigation-compose = "1.2.0"
navigation-runtime-ktx = "2.8.3"
hilt = "2.52"
ksp = "2.0.21-1.0.25"
compose-bom = "2024.10.00"
compose = "1.7.4"
room = "2.6.1"
navigation = "2.7.7"
constraint-layout = "1.1.0"
glide = "4.16.0"

coroutine-core-ver = "1.9.0"
coroutine-lifecycle-ver = "2.8.7"
appcompat = "1.7.0"
activity = "1.9.3"
constraintlayout = "2.2.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons-extended" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraint-layout-compose" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigation-runtime-ktx" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging-compose" }
material = { module = "com.google.android.material:material", version.ref = "material" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
landscapist-coil = { module = "com.github.skydoves:landscapist-coil", version.ref = "landscapist" }
landscapist-placeholder = { module = "com.github.skydoves:landscapist-placeholder", version.ref = "landscapist" }
landscapist-animation = { module = "com.github.skydoves:landscapist-animation", version.ref = "landscapist" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

coroutine-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" , version.ref = "coroutine-core-ver"}
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android" , version.ref = "coroutine-core-ver"}
coroutine-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx" , version.ref = "coroutine-lifecycle-ver"}
coroutine-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx" , version.ref = "coroutine-lifecycle-ver"}


#Navigation Components
navigation-fragment-ktx = {  group = "androidx.navigation" , name = "navigation-fragment-ktx", version.ref = "navigation"}
navigation-ui-ktx = { group = "androidx.navigation" , name = "navigation-ui-ktx", version.ref = "navigation"}

#Constraint Layout
constaint-layout = { group = "com.android.support.constraint", name = "constraint-layout", version.ref = "constraint-layout"}

#glide
glide-image = {group = "com.github.bumptech.glide", name = "glide", version.ref = "glide"}
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlinAndroidKsp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }